# Generated by Django 3.2.9 on 2022-01-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien_immo',
            name='prix_tva_normale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
