# Generated by Django 3.2.9 on 2022-01-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0002_alter_bien_immo_prix_tva_normale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien_immo',
            name='adresse_entiere',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='balcony',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='date_extraction',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='date_fin_programme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='departement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='exterieur',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='garden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='id_lot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='nb_piece',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='orientation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='parking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='prix_HT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='prix_m2_HT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='prix_m2_TTC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='prix_tva_reduite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='typologie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien_immo',
            name='ville',
            field=models.TextField(blank=True, null=True),
        ),
    ]
